package ec.edu.ucuenca.registrotramitesdth;

/**
 * This class was automatically generated by the data modeler tool.
 */

@javax.persistence.Entity
public class dth_rrt_reasignacion implements java.io.Serializable
{

   static final long serialVersionUID = 1L;

   @javax.persistence.GeneratedValue(generator = "DTH_RRT_REASIGNACION_ID_GENERATOR", strategy = javax.persistence.GenerationType.AUTO)
   @javax.persistence.Id
   @javax.persistence.SequenceGenerator(sequenceName = "DTH_RRT_REASIGNACION_ID_SEQ", name = "DTH_RRT_REASIGNACION_ID_GENERATOR")
   private java.lang.Long id;

   @org.kie.api.definition.type.Label(value = "Accion a Realizar")
   private java.lang.String accionARealizar;

   @org.kie.api.definition.type.Label(value = "Fecha")
   private java.util.Date fecha;

   @org.kie.api.definition.type.Label(value = "Usuario Destino")
   private java.lang.String usuarioDestion;

   public dth_rrt_reasignacion()
   {
   }

   public java.lang.Long getId()
   {
      return this.id;
   }

   public void setId(java.lang.Long id)
   {
      this.id = id;
   }

   public java.lang.String getAccionARealizar()
   {
      return this.accionARealizar;
   }

   public void setAccionARealizar(java.lang.String accionARealizar)
   {
      this.accionARealizar = accionARealizar;
   }

   public java.util.Date getFecha()
   {
      return this.fecha;
   }

   public void setFecha(java.util.Date fecha)
   {
      this.fecha = fecha;
   }

   public java.lang.String getUsuarioDestion()
   {
      return this.usuarioDestion;
   }

   public void setUsuarioDestion(java.lang.String usuarioDestion)
   {
      this.usuarioDestion = usuarioDestion;
   }

   public dth_rrt_reasignacion(java.lang.Long id,
         java.lang.String accionARealizar, java.util.Date fecha,
         java.lang.String usuarioDestion)
   {
      this.id = id;
      this.accionARealizar = accionARealizar;
      this.fecha = fecha;
      this.usuarioDestion = usuarioDestion;
   }

}